name: ggj2025_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flame: ^1.23.0
  flame_audio: 2.10.7
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/background/common/
    - assets/images/background/level_1/
    - assets/images/background/level_2/
    - assets/images/heroes/Dude_Monster/
    - assets/images/heroes/Owlet_Monster/
    - assets/images/heroes/Pink_Monster/
